#!/usr/bin/env python

import logging
import shutil
import subprocess
import sys
import os
import glob

logging.basicConfig(level=logging.INFO)

folder_name = 'spinnaker-1.27.0.48-amd64'
destination_folder = sys.argv[2]


if not os.path.exists(os.path.join(os.getcwd(), "usr/lib/")):
    # Unpack all debs
    logging.info("Unpacking debs.")
    debs = glob.glob(os.path.join(os.getcwd(), folder_name, "libspinvideo-*.deb"))
    debs += glob.glob(os.path.join(os.getcwd(), folder_name, "*spinnaker-*.deb"))
    for deb in debs:
        subprocess.call(['dpkg', '-x', deb, os.path.join(os.getcwd(), folder_name)])

    if not os.path.exists(os.path.join(os.getcwd(), "usr")):
        os.mkdir(os.path.join(os.getcwd(), "usr"))

    # For every folder/file, copy it into the /usr folder we just created.
    for filename in os.listdir(os.path.join(os.getcwd(), folder_name, "usr")):
        if not os.path.exists(os.path.join(os.getcwd(), "usr", filename)):
            shutil.move(os.path.join(os.getcwd(), folder_name, "usr", filename), os.path.join(os.getcwd(), "usr", filename))

    # now we do some thing for XML files; copy them next to the catkin binary
    xml_path = os.path.join(os.getcwd(), "usr/lib/")
    xml_files = os.listdir(xml_path)

    try:
        os.makedirs(destination_folder)
    except:
        logging.info("Error XML folder either exists or can't be created.")

    for files in xml_files:
        if files.endswith(".xml"):
            origin_file = os.path.join(xml_path, files)
            print('Copying ' + origin_file + ' to ' + destination_folder)
            shutil.copy(origin_file, destination_folder)